### ISSUE TITLE
Licenses screen - Error when sorting by "License Issue Date"

### ISSUE THREAD

**Issue by benface** [craftcms/commerce-digital-products#10]
On the Licenses screen, when I try to sort by "License Issue Date", I get "An unknown error occurred".

**Comment by andris-sevcenko** [comment]
Seems to be fixed as of 495cd77da3c41dae1b751db03855b1fcbd725536, will close after a release.

**Comment by andris-sevcenko** [comment]
Eh, I'll just close it now as a duplicate of #11
