### ISSUE TITLE
Title blank after upgrade of Craft & Commerce to v5

### ISSUE THREAD

**Issue by rob-c-baker** [craftcms/commerce-digital-products#103]
### Description

After following docs for upgrade (in DEV env) the digital products screen looks like this:

![image](https://github.com/user-attachments/assets/bdf7db50-fbd4-49e5-a8e3-cbae8cb42cbb)

When double clicking a row, it shows the `title` field never got populated:

![image](https://github.com/user-attachments/assets/b97ead0e-7523-4e7a-a44d-58ec0e6ee44c)

### Steps to reproduce

1. Have digital products on up-to-date versions of Craft 4 / Commerce 4
2. Perform upgrade
3. Check the screens above

### Additional info

- Craft version: 5.3.4
- PHP version: 8.3.7
- Database driver & version: MySQL 8.0.34
- Plugins & versions:

Asset Rev	8.0.0
CKEditor	4.2.0
CP Field Inspect	2.0.2
Craft Commerce	5.0.16
Digital Download	3.1.1
Digital Products	4.0.0
Elements Panel	3.0.0
Minify	5.0.0
Navigation	3.0.3
PayPal Checkout for Craft Commerce	3.0.1
SEOmatic	5.1.1
Stripe for Craft Commerce	5.0.4.2

**Comment by rob-c-baker** [comment]
Any update on this? Just attempted the upgrade again in a non-live environment and got the same thing.

Versions different from above:

Craft CMS: 5.4.1
Craft Commerce 5.1.0

~Digital download remained the same at 3.1.1~ Digital products remained the same at 4.0.0

**Comment by lukeholder** [comment]
We have just released a fixed version of the digital products plugin: 4.0.1

Please let us know if that works for you.

**Comment by rob-c-baker** [comment]
This has worked great - many thanks.
