### ISSUE TITLE
Bug in LicenseQuery

### ISSUE THREAD

**Issue by putyourlightson** [craftcms/commerce-digital-products#11]
This [line](https://github.com/craftcms/commerce-digital-products/blob/master/src/elements/db/LicenseQuery.php#L402) is throwing a "column not found" error, it should be:

`$this->subQuery->andWhere(Db::parseParam('digitalproducts_licenses.productId', $this->productId));`

Version: 2.0.2

**Comment by lazlo-bonin** [comment]
Same for orderId, it should be:

```
        if ($this->orderId) {
            $this->subQuery->andWhere(Db::parseParam('digitalproducts_licenses.orderId', $this->orderId));
        }
```

**Comment by lazlo-bonin** [comment]
Is this plugin abandoned @andris-sevcenko ? This issue and plenty of others are pretty big but easy to fix. Considering forking the repository just to fix them.

**Comment by andris-sevcenko** [comment]
Also, pull requests are always welcome. We have finite resources as well and appreciate the help :)

**Comment by lazlo-bonin** [comment]
I apologize for coming off a bit harsh, I understand these things take time. I just hadn't seen a post from a contributor on this repo in a while and was wondering if it was wise to continue to use it in production.

My own resources are spread pretty thin as well unfortunately, but if I can find the time I'll try forking and submitting a few PRs.

**Comment by andris-sevcenko** [comment]
@lazlo-bonin not offended in the slightest. I should have reacted at least, even if I was busy.

I'm guessing I'll be resuming work on this in two weeks or so. If your timeline is more pressing, you can just hot-patch your install and submit PR at your leisure. There's no pressure.

This can definitely be used in production. The only possible way this plugin ends its life I can imagine at this point if it just gets rolled into Commerce itself.
