### ISSUE TITLE
Licenses don't get assigned to newly-registered users when email verification is disabled

### ISSUE THREAD

**Issue by benface** [craftcms/commerce-digital-products#18]
If "Verify email addresses?" is disabled in the Craft User Settings and a license is purchased via guest checkout, when the user eventually registers, the license is not assigned to them. That is because the code that assigns unassigned licenses is only called when `UsersService::EVENT_AFTER_ACTIVATE_USER` is triggered, and that event is never triggered when email verification is disabled since users are active as soon as they're created (that seems to be by design, but if that is the bug, let me know and I will create an issue in the main Craft CMS repo).

**Comment by brandonkelly** [comment]
@benface Thanks for pointing that out! It was a Craft bug but the fix was easy enough so no need to repost :)

**Comment by benface** [comment]
Thanks @brandonkelly!
