### ISSUE TITLE
Product element misses method `getIsAvailable`

### ISSUE THREAD

**Issue by nilsenpaul** [craftcms/commerce-digital-products#2]
After installation of this plugin, I get a fatal error on multiple pages, saying:

`Class craft\digitalproducts\elements\Product contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (craft\commerce\base\PurchasableInterface::getIsAvailable)`

Adding this method to the element, solves this issue (duh).

**Comment by andris-sevcenko** [comment]
That's what you get when you're using alpha version software! :)
