### ISSUE TITLE
Licenses are assigned to users even if the order is not paid

### ISSUE THREAD

**Issue by alexstojda** [craftcms/commerce-digital-products#21]
## Brief description of the issue
If a user attempts to pay for an invoice and the payment fails, resulting in an order status of `unpaid`, the license is still attributed to the client. 

## Suggested resolution
Either prevent the attribution of licences for unpaid bills (EG hook the attribution to the `EVENT_AFTER_PROCESS_PAYMENT_EVENT` of commerce and validate that the transaction was PAID) or have a configuration setting to toggle the behaviour between the suggested resolution and the current behaviour.

**Comment by andris-sevcenko** [comment]
This is waiting on the next release of Craft Commerce (craftcms/commerce@8ba9a96fb35eb78be65575d6f8e4ccf1475288c6)

**Comment by alexstojda** [comment]
Perfect, thanks for the update @andris-sevcenko !

**Comment by alexstojda** [comment]
@andris-sevcenko looks like it was released! https://github.com/craftcms/commerce/releases/tag/2.0.0-beta.12

**Comment by andris-sevcenko** [comment]
@alexstojda yeah it was. Seems like a small bug in the logic, still, for payments using 3D Secure with Stripe. It's not on Digital Products' end, though, so probably going to release that today, just things might not work yet with Stripe and 3DSecure until next Commerce release, after all. Sorry :/

**Comment by andris-sevcenko** [comment]
Closed this as this is now a Commerce bug instead of Digital Products bug.
